FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app

ENV TZ=Asia/Ho_Chi_Minh
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY *.csproj ./
RUN dotnet restore

COPY . ./

EXPOSE 5000
ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000", "--non-interactive"]